import React, { useState } from 'react';
import { SyllabusItem, Exam, AIStudyAdvice } from '../types';
import { generateStudyStrategy } from '../services/aiService';
import { BrainIcon } from './Icons';

interface AICoachProps {
  syllabus: SyllabusItem[];
  exams: Exam[];
}

const AICoach: React.FC<AICoachProps> = ({ syllabus, exams }) => {
  const [advice, setAdvice] = useState<AIStudyAdvice | null>(null);
  const [loading, setLoading] = useState(false);

  const handleGenerate = async () => {
    setLoading(true);
    const result = await generateStudyStrategy(syllabus, exams);
    setAdvice(result);
    setLoading(false);
  };

  const isError = advice?.message.includes("API Key") || advice?.message.includes("network");

  return (
    <div className="max-w-3xl mx-auto space-y-8">
      <div className="text-center space-y-4">
        <div className="bg-indigo-100 dark:bg-indigo-900/40 w-16 h-16 rounded-full flex items-center justify-center mx-auto transition-colors">
          <BrainIcon className="w-8 h-8 text-indigo-600 dark:text-indigo-400" />
        </div>
        <h2 className="text-3xl font-bold text-slate-900 dark:text-white">Adaptive Study Coach</h2>
        <p className="text-slate-500 dark:text-slate-400 max-w-lg mx-auto">
          Roncate analyzes your incomplete syllabus topics and upcoming exam dates to create the perfect study plan for right now.
        </p>
      </div>

      <div className="flex justify-center">
        <button
          onClick={handleGenerate}
          disabled={loading}
          className="bg-indigo-600 hover:bg-indigo-700 dark:bg-indigo-500 dark:hover:bg-indigo-600 text-white px-8 py-3 rounded-full font-bold shadow-lg transition-all disabled:opacity-70 flex items-center gap-2"
        >
          {loading ? (
            <>
              <svg className="animate-spin h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
              </svg>
              Analyzing Progress (Llama 3.1)...
            </>
          ) : (
            'Generate Strategy'
          )}
        </button>
      </div>

      {advice && (
        <div className={`rounded-2xl shadow-lg border overflow-hidden animate-fade-in-up ${isError ? 'bg-red-50 dark:bg-red-900/20 border-red-200 dark:border-red-900' : 'bg-white dark:bg-slate-800 border-indigo-100 dark:border-slate-700'}`}>
          <div className={`${isError ? 'bg-red-500 dark:bg-red-700' : 'bg-indigo-600 dark:bg-indigo-700'} px-6 py-4`}>
            <h3 className="text-white font-bold text-lg">{isError ? 'Configuration Error' : 'Your Personalized Strategy'}</h3>
            <p className={`${isError ? 'text-red-100' : 'text-indigo-200'} text-sm`}>{isError ? 'Action Required' : 'Generated by Llama 3.1 AI'}</p>
          </div>
          <div className="p-8 space-y-6">
            <div>
              <h4 className="text-sm uppercase tracking-wide text-slate-400 dark:text-slate-500 font-bold mb-2">{isError ? 'System Message' : 'Coach\'s Advice'}</h4>
              <p className={`${isError ? 'text-red-700 dark:text-red-300 font-medium' : 'text-slate-700 dark:text-slate-300'} text-lg leading-relaxed`}>{advice.message}</p>
            </div>

            {!isError && (
              <div className="bg-slate-50 dark:bg-slate-700/50 rounded-xl p-6 border border-slate-100 dark:border-slate-600 transition-colors">
                <h4 className="text-sm uppercase tracking-wide text-indigo-600 dark:text-indigo-400 font-bold mb-4">Focus Topics for Today</h4>
                <ul className="space-y-3">
                  {advice.priorityTopics.map((topic, idx) => (
                    <li key={idx} className="flex items-center gap-3">
                      <span className="flex-shrink-0 w-6 h-6 rounded-full bg-indigo-600 dark:bg-indigo-500 text-white flex items-center justify-center text-xs font-bold">
                        {idx + 1}
                      </span>
                      <span className="font-medium text-slate-800 dark:text-slate-200">{topic}</span>
                    </li>
                  ))}
                  {advice.priorityTopics.length === 0 && <li className="text-slate-400 dark:text-slate-500 italic">No specific topics suggested.</li>}
                </ul>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
};

export default AICoach;